<?php

/**
 * BaseTransfer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $destination_id
 * @property text $description
 * @property integer $min_pax
 * @property integer $max_pax
 * @property string $round_trip
 * @property numeric $price
 * @property boolean $active
 * @property Destination $Destination
 * 
 * @method integer     getDestinationId()  Returns the current record's "destination_id" value
 * @method text        getDescription()    Returns the current record's "description" value
 * @method integer     getMinPax()         Returns the current record's "min_pax" value
 * @method integer     getMaxPax()         Returns the current record's "max_pax" value
 * @method string      getRoundTrip()      Returns the current record's "round_trip" value
 * @method numeric     getPrice()          Returns the current record's "price" value
 * @method boolean     getActive()         Returns the current record's "active" value
 * @method Destination getDestination()    Returns the current record's "Destination" value
 * @method Transfer    setDestinationId()  Sets the current record's "destination_id" value
 * @method Transfer    setDescription()    Sets the current record's "description" value
 * @method Transfer    setMinPax()         Sets the current record's "min_pax" value
 * @method Transfer    setMaxPax()         Sets the current record's "max_pax" value
 * @method Transfer    setRoundTrip()      Sets the current record's "round_trip" value
 * @method Transfer    setPrice()          Sets the current record's "price" value
 * @method Transfer    setActive()         Sets the current record's "active" value
 * @method Transfer    setDestination()    Sets the current record's "Destination" value
 * 
 * @package    atc
 * @subpackage model
 * @author     Jorgo Miridis <jorgo@miridis.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransfer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transfer');
        $this->hasColumn('destination_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('min_pax', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('max_pax', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('round_trip', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('price', 'numeric', 10, array(
             'type' => 'numeric',
             'size' => 10,
             'scale' => 2,
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Destination', array(
             'local' => 'destination_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}