<?php

/**
 * BaseTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $tx_id
 * @property string $tx_type
 * @property integer $reservation_id
 * @property text $tx_parameters
 * @property Reservation $Reservation
 * 
 * @method string      getTxId()           Returns the current record's "tx_id" value
 * @method string      getTxType()         Returns the current record's "tx_type" value
 * @method integer     getReservationId()  Returns the current record's "reservation_id" value
 * @method text        getTxParameters()   Returns the current record's "tx_parameters" value
 * @method Reservation getReservation()    Returns the current record's "Reservation" value
 * @method Transaction setTxId()           Sets the current record's "tx_id" value
 * @method Transaction setTxType()         Sets the current record's "tx_type" value
 * @method Transaction setReservationId()  Sets the current record's "reservation_id" value
 * @method Transaction setTxParameters()   Sets the current record's "tx_parameters" value
 * @method Transaction setReservation()    Sets the current record's "Reservation" value
 * 
 * @package    atc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: BaseTransaction.class.php 33 2011-02-11 18:47:27Z jorgo $
 */
abstract class BaseTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transaction');
        $this->hasColumn('tx_id', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('tx_type', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('reservation_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('tx_parameters', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reservation', array(
             'local' => 'reservation_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}