<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property string $email_address
 * @property text $message
 * @property Client $Client
 * 
 * @method integer get()              Returns the current record's "client_id" value
 * @method string  get()              Returns the current record's "email_address" value
 * @method text    get()              Returns the current record's "message" value
 * @method Client  get()              Returns the current record's "Client" value
 * @method Message set()              Sets the current record's "client_id" value
 * @method Message set()              Sets the current record's "email_address" value
 * @method Message set()              Sets the current record's "message" value
 * @method Message set()              Sets the current record's "Client" value
 * 
 * @package    atc
 * @subpackage model
 * @author     Jorgo Miridis <jorgo@miridis.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('client_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('email_address', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('message', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}