<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/12/16 17:50:20
sfConfig::add(array(
  'app_es_uri_encryption_plugin_debug' => false,
  'app_es_uri_encryption_plugin_authenticate' => false,
  'app_es_paypal_plugin_handler' => 'esPaypalHandlerATC',
  'app_es_paypal_plugin_test_mode' => false,
  'app_es_paypal_plugin_debug_mode' => true,
  'app_es_paypal_plugin_business' => 'payments@americantransferscancun.com',
  'app_es_paypal_plugin_return_method' => 2,
  'app_es_paypal_plugin_image_url' => 'https://www.paypal.com/en_US/i/btn/btn_paynowCC_LG.gif',
  'app_es_paypal_plugin_certificate' => array (
  'cert_id' => 'Z7VVARK7VYCA2',
  'ewp_prvkey_fname' => 'W:\\Projects\\atcsf1\\data/certificates/prvkey_Z7VVARK7VYCA2.pem',
  'ewp_cert_fname' => 'W:\\Projects\\atcsf1\\data/certificates/cert_Z7VVARK7VYCA2.pem',
  'pp_cert_fname' => 'W:\\Projects\\atcsf1\\data/certificates/paypal_Z7VVARK7VYCA2.pem',
),
  'app_es_paypal_plugin_callback' => NULL,
  'app_es_paypal_plugin_checkout' => array (
  'page_style' => 'primary',
  'image_url' => 'http://americantransferscancun.com/images/paypal-logo.png',
  'cpp_header_image' => 'http://americantransferscancun.com/images/paypal-header.png',
  'cbt' => 'Return to Your Reservation at ATC',
),
  'app_es_email_plugin_layoutDir' => 'W:\\Projects\\atcsf1\\lib/email/templates',
  'app_es_email_plugin_templateDir' => 'W:\\Projects\\atcsf1\\lib/email/modules',
  'app_es_email_plugin_autoEmbedImages' => true,
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
  'app_esUriEncryptionPlugin_debug' => true,
  'app_esUriEncryptionPlugin_authenticate' => true,
  'app_email_from' => 'reservation@americantransferscancun.com',
  'app_email_bcc' => 'reservation@americantransferscancun.com',
  'app_email_contact' => 'contact@americantransferscancun.com',
));
