<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/12/16 17:50:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf_atc',
  'username' => 'root',
  'password' => 'D3lph1',
  'name' => 'doctrine',
)),);
