<?php

/**
 * PaypalTransaction
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    atc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: PaypalTransaction.class.php 36 2011-03-10 01:20:24Z jorgo $
 */
class PaypalTransaction extends PluginPaypalTransaction
{
  public function __toString()
  {
    return $this->txn_id;
  }
}