<?php

/**
 * PaypalTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaypalTransactionTable extends PluginPaypalTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaypalTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaypalTransaction');
    }
}