<?php

/**
 * DestinationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DestinationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DestinationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Destination');
    }
}