<?php

/**
 * Destination
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    atc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Destination.class.php 33 2011-02-11 18:47:27Z jorgo $
 */
class Destination extends BaseDestination
{
  public function __toString()
  {
    return $this->title;
  }
}