<?php

/**
 * ReservationTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservationTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ReservationTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Reservation');
  }


  public static function getNotDeleted($client_id)
    {
      return Doctrine_Core::getTable('Reservation')
        ->createQuery('a')
        ->where('client_id=?', $client_id)
        ->andWhere('not deleted')
        ->orderBy('created_at DESC')
        ->execute();
    }
}