<?php

/**
 * TransferTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransferTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransferTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Transfer');
    }

  public static function getPrice($destination_id, $round_trip, $no_pax)
  {
    $q = Doctrine_Query::create()
      ->select('price')
      ->from('Transfer t')
      ->where('t.destination_id = ?', $destination_id)
      ->andWhere('t.min_pax <= ?', $no_pax)
      ->andWhere('t.max_pax >= ?', $no_pax)
      ->andWhere('t.round_trip = ?', $round_trip)
      ->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR);

    return $q->execute();
  }

  public static function getActivePrices()
  {
    //--------------------------------------------------------------------------
    // retrieve transfer records
    //--------------------------------------------------------------------------
    $q = Doctrine_Query::create()
      ->from('Transfer t')
      ->andWhere('t.active')
      ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
    //--------------------------------------------------------------------------
    // create price records suitable to be managed by JS client code
    // e.g. $prices["1|1-4|RT"] = 55;
    // json_encode =>  ["1|1-4|RT":"55",...]
    //--------------------------------------------------------------------------
    $prices = array();
    foreach($q->execute() as $record)
    {
      $key = sprintf('%s|%s-%s|%s',
        $record['destination_id'],
        $record['min_pax'],
        $record['max_pax'],
        $record['round_trip']
      );

      $prices[$key] = $record['price'];
    }
    return $prices;
  }
}