<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/12/16 17:34:48
sfConfig::add(array(
  'app_es_uri_encryption_plugin_debug' => false,
  'app_es_uri_encryption_plugin_authenticate' => false,
  'app_es_paypal_plugin_handler' => 'esPaypalHandlerATC',
  'app_es_paypal_plugin_test_mode' => true,
  'app_es_paypal_plugin_debug_mode' => true,
  'app_es_paypal_plugin_business' => 'sales_1296405385_biz@miridis.com',
  'app_es_paypal_plugin_return_method' => 2,
  'app_es_paypal_plugin_image_url' => 'https://www.paypal.com/en_US/i/btn/btn_paynowCC_LG.gif',
  'app_es_paypal_plugin_certificate' => array (
  'cert_id' => 'ERC56ZCBB6AVY',
  'ewp_prvkey_fname' => 'W:\\Projects\\atcsf1\\plugins/esPaypalPlugin/data/certificates/plugin-prvkey.pem',
  'ewp_cert_fname' => 'W:\\Projects\\atcsf1\\plugins/esPaypalPlugin/data/certificates/plugin-pubcert.pem',
  'pp_cert_fname' => 'W:\\Projects\\atcsf1\\plugins/esPaypalPlugin/data/certificates/paypal-pubcert.pem',
),
  'app_es_paypal_plugin_callback' => NULL,
  'app_es_paypal_plugin_checkout' => NULL,
  'app_sf_guard_plugin_allow_login_with_email' => false,
  'app_sf_guard_plugin_success_signout_url' => '@login',
  'app_sf_guard_plugin_success_signin_url' => '@reservation',
  'app_esUriEncryptionPlugin_debug' => true,
  'app_esUriEncryptionPlugin_authenticate' => true,
));
