<?php

/**
 * sfGuardGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    atc
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: sfGuardGroupPermission.class.php 33 2011-02-11 18:47:27Z jorgo $
 */
class sfGuardGroupPermission extends PluginsfGuardGroupPermission
{

}