<?php

/**
 * BasePaypalTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_id
 * @property string $txn_id
 * @property string $txn_type
 * @property string $status
 * @property text $ipn_data
 * @property Reservation $Reservation
 * 
 * @method integer           get()            Returns the current record's "parent_id" value
 * @method string            get()            Returns the current record's "txn_id" value
 * @method string            get()            Returns the current record's "txn_type" value
 * @method string            get()            Returns the current record's "status" value
 * @method text              get()            Returns the current record's "ipn_data" value
 * @method Reservation       get()            Returns the current record's "Reservation" value
 * @method PaypalTransaction set()            Sets the current record's "parent_id" value
 * @method PaypalTransaction set()            Sets the current record's "txn_id" value
 * @method PaypalTransaction set()            Sets the current record's "txn_type" value
 * @method PaypalTransaction set()            Sets the current record's "status" value
 * @method PaypalTransaction set()            Sets the current record's "ipn_data" value
 * @method PaypalTransaction set()            Sets the current record's "Reservation" value
 * 
 * @package    atc
 * @subpackage model
 * @author     Jorgo Miridis <jorgo@miridis.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaypalTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paypal_transaction');
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('txn_id', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('txn_type', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('status', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('ipn_data', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reservation', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}