<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('reservation', 'firstname', 'string', '50', array(
            'notnull' => '',
        ));
        $this->addColumn('reservation', 'lastname', 'string', '50', array(
            'notnull' => '',
        ));
    }

    public function down()
    {
        $this->removeColumn('reservation', 'firstname');
        $this->removeColumn('reservation', 'lastname');
    }
}