<?php

/**
 * PluginPaypalTransactionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPaypalTransactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPaypalTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPaypalTransaction');
    }

    public function existsIdAndStatus($txn_id, $status)
    {
      $count = Doctrine_Query::create()
        ->select('count(*)')
        ->from('PaypalTransaction')
        ->where('txn_id=?', $txn_id)
        ->andWhere('status=?', $status)
        ->setHydrationMode(Doctrine::HYDRATE_SINGLE_SCALAR)
        ->execute();

      return ($count != 0);
    }
}

