generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Transfer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          transfer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:
        display: [ destination_id, description, min_pax, max_pax, round_trip, price, active ]
        fields: [ destination_id, description, min_pax, max_pax, round_trip, price, active ]
